{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "MappingConverter",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "e6cpbk4affa6fjeqbbktju2xoq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14)",
            "requires": "[2.13.1,2.14)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13.0-RC3",
          "version": {
            "strictly": "[1.1.2,)",
            "requires": "[1.1.2,)",
            "prefers": "1.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "strictly": "[1.9,)",
            "requires": "[1.9,)",
            "prefers": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.6,)",
            "requires": "[2.8.6,)",
            "prefers": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "MappingConverter-1.0.2.jar",
          "url": "MappingConverter-1.0.2.jar",
          "size": 399729,
          "sha512": "05b7f2a675bb1b0bebfc2e76d09ad13fd6a903abfe3cd861576b83f392652bea0a84431f8ae183a884be9601ff9abf1d866186e0b43d31253123f76cbb1ebc3f",
          "sha256": "8796e0c194d2b84f91e970539f12560ceddcebbf023bb6e5a6ef1b4d71072a63",
          "sha1": "7fac572d6944a6ec8920a3d5119167c2d3761839",
          "md5": "9307cef6743ae8a1b28a0fc081459c3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14)",
            "requires": "[2.13.1,2.14)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13.0-RC3",
          "version": {
            "strictly": "[1.1.2,)",
            "requires": "[1.1.2,)",
            "prefers": "1.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "strictly": "[1.9,)",
            "requires": "[1.9,)",
            "prefers": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.6,)",
            "requires": "[2.8.6,)",
            "prefers": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "MappingConverter-1.0.2.jar",
          "url": "MappingConverter-1.0.2.jar",
          "size": 399729,
          "sha512": "05b7f2a675bb1b0bebfc2e76d09ad13fd6a903abfe3cd861576b83f392652bea0a84431f8ae183a884be9601ff9abf1d866186e0b43d31253123f76cbb1ebc3f",
          "sha256": "8796e0c194d2b84f91e970539f12560ceddcebbf023bb6e5a6ef1b4d71072a63",
          "sha1": "7fac572d6944a6ec8920a3d5119167c2d3761839",
          "md5": "9307cef6743ae8a1b28a0fc081459c3e"
        }
      ]
    }
  ]
}
