{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "MappingConverter",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "wf3bxwhrprd6nivffs6pht3in4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14)",
            "requires": "[2.13.1,2.14)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13.0-RC3",
          "version": {
            "strictly": "[1.1.2,)",
            "requires": "[1.1.2,)",
            "prefers": "1.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "strictly": "[1.9,)",
            "requires": "[1.9,)",
            "prefers": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.6,)",
            "requires": "[2.8.6,)",
            "prefers": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "MappingConverter-1.0.5.jar",
          "url": "MappingConverter-1.0.5.jar",
          "size": 402885,
          "sha512": "ecd9ec5c8726ce0632f71a8872243280f927563e8c370a925c8cef2c595042da83ddd050b1c61d9064e2d60f1324c70dfb098da1cd27865662c7c4df5b524796",
          "sha256": "2a8563bc3a9de2ee9a76e41ef4bc414bac546426db9e2111b72dbf7a21f1cd79",
          "sha1": "a303c72d2160df6e8807ea9ea6de52edf22eb517",
          "md5": "021aab5ab70460cacf1f533034a4f99e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14)",
            "requires": "[2.13.1,2.14)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13.0-RC3",
          "version": {
            "strictly": "[1.1.2,)",
            "requires": "[1.1.2,)",
            "prefers": "1.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "strictly": "[1.9,)",
            "requires": "[1.9,)",
            "prefers": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.6,)",
            "requires": "[2.8.6,)",
            "prefers": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "MappingConverter-1.0.5.jar",
          "url": "MappingConverter-1.0.5.jar",
          "size": 402885,
          "sha512": "ecd9ec5c8726ce0632f71a8872243280f927563e8c370a925c8cef2c595042da83ddd050b1c61d9064e2d60f1324c70dfb098da1cd27865662c7c4df5b524796",
          "sha256": "2a8563bc3a9de2ee9a76e41ef4bc414bac546426db9e2111b72dbf7a21f1cd79",
          "sha1": "a303c72d2160df6e8807ea9ea6de52edf22eb517",
          "md5": "021aab5ab70460cacf1f533034a4f99e"
        }
      ]
    }
  ]
}
