{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.noeppi_noeppi.tools",
    "module": "MappingConverter",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "l5bocpdamfcstkiavbhhzelmty"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14)",
            "requires": "[2.13.1,2.14)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13.0-RC3",
          "version": {
            "strictly": "[1.1.2,)",
            "requires": "[1.1.2,)",
            "prefers": "1.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "strictly": "[1.9,)",
            "requires": "[1.9,)",
            "prefers": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.6,)",
            "requires": "[2.8.6,)",
            "prefers": "2.8.6"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "MappingConverter-1.0.8.jar",
          "url": "MappingConverter-1.0.8.jar",
          "size": 410464,
          "sha512": "9e78710bc3b94306b3172b1c55fafe5c28e7cc3fbc59f3b34c47234ba69d802a31cafff6cc55eca796a4ea5f85d1c355170da08dbc215d73c057c12e1da1a455",
          "sha256": "31f90fe4a2d11ed74ab87b556f8a1027713b4ac5a122a29a2ffcd1a837828469",
          "sha1": "dc51588f883b57a88550e088eb0fdbb094234ad6",
          "md5": "376324c91d8bd9fd227866c1c6d7d4c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "strictly": "[2.13.1,2.14)",
            "requires": "[2.13.1,2.14)",
            "prefers": "2.13.1"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-parser-combinators_2.13.0-RC3",
          "version": {
            "strictly": "[1.1.2,)",
            "requires": "[1.1.2,)",
            "prefers": "1.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "strictly": "[1.9,)",
            "requires": "[1.9,)",
            "prefers": "1.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "strictly": "[2.8.6,)",
            "requires": "[2.8.6,)",
            "prefers": "2.8.6"
          }
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "strictly": "[2.0.0,)",
            "requires": "[2.0.0,)",
            "prefers": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "MappingConverter-1.0.8.jar",
          "url": "MappingConverter-1.0.8.jar",
          "size": 410464,
          "sha512": "9e78710bc3b94306b3172b1c55fafe5c28e7cc3fbc59f3b34c47234ba69d802a31cafff6cc55eca796a4ea5f85d1c355170da08dbc215d73c057c12e1da1a455",
          "sha256": "31f90fe4a2d11ed74ab87b556f8a1027713b4ac5a122a29a2ffcd1a837828469",
          "sha1": "dc51588f883b57a88550e088eb0fdbb094234ad6",
          "md5": "376324c91d8bd9fd227866c1c6d7d4c0"
        }
      ]
    }
  ]
}
